// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdYLzaPGvLBny4Z4U4Cyzn9BeiWbTVOvs',
    appId: '1:538270264531:web:db6e9f94e5e8678f787826',
    messagingSenderId: '538270264531',
    projectId: 'reddit-clone-5ce31',
    authDomain: 'reddit-clone-5ce31.firebaseapp.com',
    storageBucket: 'reddit-clone-5ce31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFfXdRSkoovR0xx6Aa8_6g1d98xg0XoI',
    appId: '1:538270264531:android:cf904ce18f6be987787826',
    messagingSenderId: '538270264531',
    projectId: 'reddit-clone-5ce31',
    storageBucket: 'reddit-clone-5ce31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA08ZqGFJdwHG5lO9UYkVqKzpUcWKwacCA',
    appId: '1:538270264531:ios:07bca46b8c73fb7d787826',
    messagingSenderId: '538270264531',
    projectId: 'reddit-clone-5ce31',
    storageBucket: 'reddit-clone-5ce31.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA08ZqGFJdwHG5lO9UYkVqKzpUcWKwacCA',
    appId: '1:538270264531:ios:07bca46b8c73fb7d787826',
    messagingSenderId: '538270264531',
    projectId: 'reddit-clone-5ce31',
    storageBucket: 'reddit-clone-5ce31.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdYLzaPGvLBny4Z4U4Cyzn9BeiWbTVOvs',
    appId: '1:538270264531:web:0118e30f080d9bce787826',
    messagingSenderId: '538270264531',
    projectId: 'reddit-clone-5ce31',
    authDomain: 'reddit-clone-5ce31.firebaseapp.com',
    storageBucket: 'reddit-clone-5ce31.appspot.com',
  );
}
